# Generated by Django 4.0 on 2023-02-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbervalidation', '0002_profile_otp_profile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobnumber',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
