# Generated by Django 4.0 on 2023-02-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbervalidation', '0003_profile_mobnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobnumber',
            field=models.CharField(max_length=20),
        ),
    ]
